/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.conversor.conversorDeNumeros.igu;

import com.conversor.conversorDeNumeros.logica.Operaciones;

/**
 *
 * @author mikic
 */
public class PantallaConversorNumeros extends javax.swing.JFrame {
    private String stringConvertirDe = "DECIMAL";
    private String stringConvertirA = "DECIMAL";

    public PantallaConversorNumeros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ConvertirA = new javax.swing.JComboBox<>();
        ConvertirDe = new javax.swing.JComboBox<>();
        NumeroAConvertir = new javax.swing.JTextField();
        TextResultado = new javax.swing.JTextField();
        BtnConvertir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ConvertirA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DECIMAL","BINARIO", "HEXA", "OCTAL" }));
        ConvertirA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertirAActionPerformed(evt);
            }
        });

        ConvertirDe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DECIMAL","BINARIO", "HEXA", "OCTAL" }));
        ConvertirDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertirDeActionPerformed(evt);
            }
        });

        BtnConvertir.setText("CONVERTIR");
        BtnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConvertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(NumeroAConvertir))
                    .addComponent(BtnConvertir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                .addComponent(ConvertirA, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TextResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(169, 169, 169)
                    .addComponent(ConvertirDe, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(359, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConvertirA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumeroAConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(TextResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(BtnConvertir)
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(ConvertirDe, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(200, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void elegirOperacion(String to,String from){
        Operaciones transformar =  new Operaciones(NumeroAConvertir.getText());
        if(to==from)TextResultado.setText(NumeroAConvertir.getText()); 
        if(to=="DECIMAL"&&from=="BINARIO")TextResultado.setText(transformar.transformarDecimalBin());
        if(to=="DECIMAL"&&from=="HEXA")TextResultado.setText(transformar.transformarDecimalHexa());
        if(to=="DECIMAL"&&from=="OCTAL")TextResultado.setText(transformar.transformarDecimalOctal());
        if(to=="BINARIO"&&from=="DECIMAL")TextResultado.setText(transformar.transformarBinDecimal());
        if(to=="HEXA"&&from=="DECIMAL")TextResultado.setText(transformar.transformarHexDecimal());
        if(to=="OCTAL"&&from=="DECIMAL")TextResultado.setText(transformar.transformarOctalDecimal());
        if(to=="BINARIO"&&from=="HEXA")TextResultado.setText(transformar.transformarBinHexa());
        if(to=="BINARIO"&&from=="OCTAL")TextResultado.setText(transformar.transformarBinOctal());
        if(to=="HEXA"&&from=="BINARIO")TextResultado.setText(transformar.transformarHexaBin());
        if(to=="OCTAL"&&from=="BINARIO")TextResultado.setText(transformar.transformarOctalBin());
        if(to=="HEXA"&&from=="OCTAL")TextResultado.setText(transformar.transformarHexaOctal());
        if(to=="OCTAL"&&from=="HEXA")TextResultado.setText(transformar.transformarOctalHexa());
    }
    private void BtnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConvertirActionPerformed
        if(NumeroAConvertir.getText() != null){
            elegirOperacion(this.stringConvertirDe, this.stringConvertirA);
        }
    }//GEN-LAST:event_BtnConvertirActionPerformed

    private void ConvertirDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertirDeActionPerformed
        this.stringConvertirDe = ConvertirDe.getSelectedItem().toString();
    }//GEN-LAST:event_ConvertirDeActionPerformed

    private void ConvertirAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertirAActionPerformed
        this.stringConvertirA = ConvertirA.getSelectedItem().toString();
    }//GEN-LAST:event_ConvertirAActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConvertir;
    private javax.swing.JComboBox<String> ConvertirA;
    private javax.swing.JComboBox<String> ConvertirDe;
    private javax.swing.JTextField NumeroAConvertir;
    private javax.swing.JTextField TextResultado;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
